version: "3.8"

services:
  backend:
    image: abdessalem/comedic_nodejs:latest
    restart: always
    ports:
      - "3000:3000"

  frontend:
    image: abdessalem/comedic_reactjs:latest
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
